#pragma once
#include "BaseSceneObject.h"
#include "SceneObjectPrimitive.h"
#include "SceneObjectTexture.h"
#include "SceneObjectMaterial.h"
#include "SceneObjectMesh.h"
#include "SceneObjectMesh.h"
#include "SceneObjectLight.h"
#include "SceneObjectCamera.h"
#include "SceneObjectTransform.h"
// #include "SceneObjectTrack.h"
// #include "SceneObjectAnimation.h"